services:
  - type: web
    name: drx-api
    runtime: image
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    image:
      url: drx-api
    buildCommand: |
      apt-get update && apt-get install -y gcc python3 python3-pip
      pip3 install flask gunicorn
      gcc khalnayak.c -o khalnayak -lpthread -O3
    startCommand: gunicorn server:app --bind 0.0.0.0:8080
    envVars:
      - key: API_KEY
        value: BHAG_BHOSDIKE_2024

  - type: worker
    name: drx-bot
    runtime: python
    buildCommand: pip install telebot requests
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8898448854:AAFPfCiuwtqVSRzZiob5ubMZ5PRbhWWfs8A
      - key: ADMIN_ID
        value: 7837187893
      - key: API_KEY
        value: BHAG_BHOSDIKE_2024
      - key: API_URL
        value: https://drx-api.onrender.com/api/strike
